### PR TITLE
use `started` lifecycle for queues

### PR DESCRIPTION
**Pull request by darky**
It resolve this problem:
https://github.com/moleculerjs/moleculer-addons/issues/27#issuecomment-426502333

### CODE REVIEW

**Comment by darky** [comment]
I don't know how to fix "out of sync problem"
Try `npm install` for regen *package-lock.json*
Even try up *package.json* dependencies
Nothing help me

**Comment by icebob** [comment]
Please fix test issues: https://travis-ci.org/moleculerjs/moleculer-addons/jobs/484703181

**Comment by darky** [comment]
Ok, tests fixed.
Problem with `snyk` still actual

**Comment by icebob** [comment]
Thanks, I'll regenerate lock files.

**Comment by icebob** [comment]
Released.

**Pull request merged**
